/**
 * Noms anglais acceptés en réponse, ajoutés aux alias par
 * generate-countries.mjs.
 *
 * Un visiteur anglophone lit souvent le site traduit par son navigateur, mais
 * il tape les réponses dans sa langue : « Germany », « Vienna ». N'y figurent
 * que les noms que la correction ne reconnaît pas déjà exactement — « Kenya »
 * ou « Berlin » s'écrivent pareil dans les deux langues.
 *
 * La correction écarte « the », « of », la ponctuation et ramène « Saint » à
 * « St » : « St. Lucia » vaut « Saint Lucia », « The Gambia » vaut « Gambia ».
 * « and » reste un mot : on donne la forme qu'un anglophone tape en entier.
 */

/** Noms de pays. */
export const NAMES_EN = {
  // Afrique
  ZA: ['South Africa'],
  DZ: ['Algeria'],
  CM: ['Cameroon'],
  CV: ['Cape Verde', 'Cabo Verde'],
  KM: ['Comoros'],
  CD: ['DR Congo', 'Democratic Republic of the Congo', 'DRC'],
  CG: ['Republic of the Congo'],
  CF: ['Central African Republic'],
  EG: ['Egypt'],
  ER: ['Eritrea'],
  ET: ['Ethiopia'],
  GM: ['Gambia'],
  GN: ['Guinea'],
  GQ: ['Equatorial Guinea'],
  GW: ['Guinea-Bissau'],
  LY: ['Libya'],
  MA: ['Morocco'],
  MR: ['Mauritania'],
  MU: ['Mauritius'],
  NA: ['Namibia'],
  ST: ['Sao Tome and Principe'],
  SO: ['Somalia'],
  SD: ['Sudan'],
  SS: ['South Sudan'],
  SZ: ['Swaziland'],
  TD: ['Chad'],
  TN: ['Tunisia'],
  TZ: ['Tanzania'],
  UG: ['Uganda'],
  ZM: ['Zambia'],
  // Amériques
  AG: ['Antigua and Barbuda'],
  AR: ['Argentina'],
  BB: ['Barbados'],
  BO: ['Bolivia'],
  BR: ['Brazil'],
  CL: ['Chile'],
  CO: ['Colombia'],
  DM: ['Dominica'],
  DO: ['Dominican Republic'],
  EC: ['Ecuador'],
  GD: ['Grenada'],
  JM: ['Jamaica'],
  KN: ['Saint Kitts and Nevis'],
  LC: ['Saint Lucia'],
  MX: ['Mexico'],
  PE: ['Peru'],
  TT: ['Trinidad and Tobago'],
  US: ['United States', 'United States of America', 'America'],
  VC: ['Saint Vincent and the Grenadines'],
  // Asie
  AE: ['United Arab Emirates', 'UAE'],
  AM: ['Armenia'],
  AZ: ['Azerbaijan'],
  BH: ['Bahrain'],
  BT: ['Bhutan'],
  CN: ['China'],
  CY: ['Cyprus'],
  GE: ['Georgia'],
  ID: ['Indonesia'],
  IN: ['India'],
  IQ: ['Iraq'],
  JO: ['Jordan'],
  JP: ['Japan'],
  KG: ['Kyrgyzstan'],
  KH: ['Cambodia'],
  KP: ['North Korea'],
  KR: ['South Korea', 'Korea'],
  KW: ['Kuwait'],
  LB: ['Lebanon'],
  MM: ['Burma'],
  MN: ['Mongolia'],
  MY: ['Malaysia'],
  SA: ['Saudi Arabia'],
  SG: ['Singapore'],
  SY: ['Syria'],
  TH: ['Thailand'],
  TJ: ['Tajikistan'],
  TL: ['East Timor'],
  TR: ['Turkey'],
  UZ: ['Uzbekistan'],
  // Europe
  AD: ['Andorra'],
  AL: ['Albania'],
  AT: ['Austria'],
  BA: ['Bosnia and Herzegovina'],
  BE: ['Belgium'],
  BG: ['Bulgaria'],
  CH: ['Switzerland'],
  CZ: ['Czechia', 'Czech Republic'],
  DE: ['Germany'],
  DK: ['Denmark'],
  EE: ['Estonia'],
  ES: ['Spain'],
  FI: ['Finland'],
  GB: ['United Kingdom', 'Britain', 'England'],
  GR: ['Greece'],
  HR: ['Croatia'],
  HU: ['Hungary'],
  IE: ['Ireland'],
  IS: ['Iceland'],
  IT: ['Italy'],
  LT: ['Lithuania'],
  LV: ['Latvia'],
  MD: ['Moldova'],
  MK: ['North Macedonia', 'Macedonia'],
  MT: ['Malta'],
  NL: ['Netherlands', 'Holland'],
  NO: ['Norway'],
  PL: ['Poland'],
  RO: ['Romania'],
  RS: ['Serbia'],
  RU: ['Russia'],
  SE: ['Sweden'],
  SI: ['Slovenia'],
  SK: ['Slovakia'],
  SM: ['San Marino'],
  VA: ['Vatican City', 'Holy See'],
  // Océanie
  AU: ['Australia'],
  FJ: ['Fiji'],
  FM: ['Micronesia'],
  MH: ['Marshall Islands'],
  NZ: ['New Zealand'],
  PG: ['Papua New Guinea'],
  PW: ['Palau'],
  SB: ['Solomon Islands'],
};

/** Capitales, quand leur nom anglais diffère du français. */
export const CAPITALS_EN = {
  // Afrique
  DZ: ['Algiers'],
  EG: ['Cairo'],
  ET: ['Addis Ababa'],
  SO: ['Mogadishu'],
  SS: ['Juba'],
  // Amériques
  CU: ['Havana'],
  GT: ['Guatemala City'],
  MX: ['Mexico City'],
  PA: ['Panama City'],
  // Asie
  AE: ['Abu Dhabi'],
  AF: ['Kabul'],
  AM: ['Yerevan'],
  AZ: ['Baku'],
  BD: ['Dhaka'],
  BT: ['Thimphu'],
  CN: ['Beijing', 'Peking'],
  IQ: ['Baghdad'],
  IR: ['Tehran'],
  KG: ['Bishkek'],
  KW: ['Kuwait City'],
  LB: ['Beirut'],
  MN: ['Ulaanbaatar', 'Ulan Bator'],
  NP: ['Kathmandu'],
  OM: ['Muscat'],
  PH: ['Manila'],
  SA: ['Riyadh'],
  SG: ['Singapore'],
  SY: ['Damascus'],
  TJ: ['Dushanbe'],
  TM: ['Ashgabat'],
  UZ: ['Tashkent'],
  // Europe
  AD: ['Andorra la Vella'],
  AT: ['Vienna'],
  BE: ['Brussels'],
  CH: ['Bern'],
  CY: ['Nicosia'],
  DK: ['Copenhagen'],
  GB: ['London'],
  GR: ['Athens'],
  MT: ['Valletta'],
  PL: ['Warsaw'],
  PT: ['Lisbon'],
  RO: ['Bucharest'],
  RU: ['Moscow'],
  SM: ['San Marino'],
  VA: ['Vatican City'],
  // Océanie
  KI: ['South Tarawa'],
};
